#!/bin/bash

export CLAMAV_LATEST=$(yum info clamav-update | grep Version | awk -F':' '{ print $2 }' | tail -n1 | tr -d '[:space:]')
echo CLAMAV_LATEST=$CLAMAV_LATEST >> workspace/clamav-latest
export REQUIRE_UPDATE=$(aws s3 ls s3://$S3_BUCKET/lambda-$CLAMAV_LATEST.zip > /dev/null; if [[ $? == 0 ]]; then echo false; else echo true; fi)
echo '{"require-update": '$REQUIRE_UPDATE'}' >> workspace/require-update.json